version: '3'
services:
  backend-gateway:
    container_name: backend-gateway
    build:
      context: ./backend-gateway
      dockerfile: Dockerfile
    ports:
      - "8101:8101"
    networks:
      - mynetwork

  backend-user-service:
    container_name: backend-user-service
    build:
      context: ./backend-user-service
      dockerfile: Dockerfile
    ports:
      - "8102:8102"
    networks:
      - mynetwork
    depends_on:
      - backend-gateway

# 网络，不定义的话就是默认网络
networks:
  mynetwork:
