spring:
  application:
    name: backend-judge-service
  # ?? dev ??
  profiles:
    active: dev
  # ?? swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session ??
  session:
    # ????????? session????? Redis?
    store-type: redis
    # 30 ???
    timeout: 2592000
  # ?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oj
    username: root
    password: root
  # Redis ??
  redis:
    database: 3
    host: 192.168.131.123
    port: 6379
    timeout: 5000
    password: 123321
    connect-timeout: 100000
  # todo rabbitmq ??
  rabbitmq:
    host: xxxxx
    password: xxxx
    username: xxxxx
    port: 5672
    virtual-host: /
    listener:
      direct:
        acknowledge-mode: manual
  #nacos
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
server:
  address: 0.0.0.0
  port: 8104
  servlet:
    context-path: /api/judge
    # cookie 30 ???
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # ????????????
      logic-delete-value: 1 # ?????????? 1?
      logic-not-delete-value: 0 # ?????????? 0?
# 代码沙箱
codesandbox:
  type: remote
# knife4j
knife4j:
  enable: true
