spring:
  application:
    name: treeoj-code-sandbox
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # 取消注释开启分布式 session（须先配置 Redis）
    store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oj
    username: root
    password: root
  # Redis 配置
  redis:
    database: 3
    host: 192.168.131.123
    port: 6379
    timeout: 5000
    password: 123321
    connect-timeout: 100000
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  # 注册到 nacos 服务
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
server:
  address: 0.0.0.0
  port: 8081
  servlet:
    context-path: /api/codesandbox
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
        path: /api
knife4j:
  enable: true